### ISSUE TITLE
ADD THE SAFER_CHECK ARGUMENT EVERYWHERE

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#1]
See 
https://github.com/safer-r/ggcute/issues/2

**Comment by Tintin2710** [comment]
1. arg_test .R:  
- [x] fun_gg_boxplot est remplacé par ggbox
- [x] ajoute package names avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'oredre

**Comment by Tintin2710** [comment]
2. arg_check.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre

**Comment by Tintin2710** [comment]
3. env_check.R:
- [x]  ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre
- [x] ajoute packagenames

**Comment by Tintin2710** [comment]
4.get_message.R:

- [x] ajoute packagenamas avant les fonctions
- [x] modifie l'ordre
- [x] ADD THE SAFER_CHECK ARGUMENT

**Comment by Tintin2710** [comment]
5.is_function_here:
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] ajoute packagenamas avant les fonctions
- [x] modifie l'ordre

**Comment by Tintin2710** [comment]
is_package_here.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre

**Comment by Tintin2710** [comment]
is_python_package_here.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre
- [x] add management of NULL arguments

**Comment by Tintin2710** [comment]
report.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre

**Comment by gael-millot** [comment]
errors fixed
