### ISSUE TITLE
Problem of ERROR message display for arguments with no default value

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#13]
The problem is one missing space in the message
saferDev::get_message()
->
FOLLOWING ARGUMENTHAS NO DEFAULT VALUE AND REQUIRE ONE:

So
check and replace in every function of all packages:
base::ifelse(base::sum(tempo, na.rm = TRUE) > 1, "S HAVE", "HAS"), " NO DEFAULT
By
base::ifelse(base::sum(tempo, na.rm = TRUE) > 1, "S HAVE", " HAS"), " NO DEFAULT

**Comment by Tintin2710** [comment]
saferDev done

**Comment by gael-millot** [comment]
Thanks !
Il faudrait le faire pour tous les packages. Ok ?

**Comment by Tintin2710** [comment]
OK！

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gael-millot ***@***.***>
发送时间: Wednesday, May 15, 2024 4:04:25 PM
收件人: safer-r/saferDev ***@***.***>
抄送: Haiding WANG ***@***.***>; State change ***@***.***>
主题: Re: [safer-r/saferDev] Problem of ERROR message display for arguments with no default value (Issue #13)


Thanks !
Il faudrait le faire pour tous les packages. Ok ?

―
