### ISSUE TITLE
check if importFrom() exists -> create it to gather all the non base:: packages:::functions used to facilitate @importFrom writting

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#25]

**Comment by Tintin2710** [comment]
sir this issue means to gather all function used which are not in basic package and create @importFrom right? Not just base:: and internal function?

**Comment by gael-millot** [comment]
Correct !

**Comment by gael-millot** [comment]
And to add it like this : 
```#' @importFrom lubridate seconds_to_period
#' @importFrom qpdf pdf_combine
#' @importFrom parallel detectCores
#' @importFrom parallel makeCluster
#' @importFrom parallel clusterSplit
#' @importFrom parallel clusterApply
#' @importFrom parallel stopCluster
```

**Comment by Tintin2710** [comment]
> And to add it like this :
> 
> ```
> #' @importFrom qpdf pdf_combine
> #' @importFrom parallel detectCores
> #' @importFrom parallel makeCluster
> #' @importFrom parallel clusterSplit
> #' @importFrom parallel clusterApply
> #' @importFrom parallel stopCluster
> ```

Yesm that's what i'm doing right now
