### ISSUE TITLE
fit the new backbone to all functions

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#27]
backbone file is here:
C:\Users\gmillot\Documents\Git_projects\safer-r\.github\profile

**Comment by gael-millot** [comment]
J’ai une question, pour l’argument ‘options’ dans la fonction arg_check, s’il peut être "" ou pas ?
1) Très bonne question. Tu as raison : cet argument options peut être "". Il faut donc ne pas le mettre dans la gestion des "".
Merci !

**Comment by Tintin2710** [comment]
Ok!!

**Comment by Tintin2710** [comment]
######## warning

      if(loop > 100){

              warn_count <- warn_count + 1

              tempo_warn <- base::paste0("(", warn_count,") THE FIRST FOR & WHILE LOOP STEPS HAVE BEEN TOO FAR AND SUBSEQUENT LOOP STEPS WILL NOT RUN", collapse = NULL, recycle0 = FALSE)

              warn <- base::paste0(base::ifelse(test = base::is.null(x = warn), yes = tempo_warn, no = base::paste0(warn, "\n\n", tempo_warn, collapse = NULL, recycle0 = FALSE)), collapse = NULL, recycle0 = FALSE)

      }

      ######## end warning

Monsieur, qu'est ce que 'est le 'loop'? quand faut ajoute waring?

**Comment by gael-millot** [comment]
Idem. Bien vu ! Il faut retirer le   if(loop > 100){
Je m'occupe d'updater le fichier backbone et le site du proto 167.
Merci !

Gael.

**Comment by Tintin2710** [comment]
![屏幕截图 2024-11-15 133907](https://github.com/user-attachments/assets/003b7937-4f10-4610-a468-9dc6b1d1a74f)
Monsieur, dans la section argument checking with arg_check() de la foncton get_message, faut supprimer cechecking ou pas, on a déjà vérifié safer_check dessus c'est ça?

**Comment by gael-millot** [comment]
Yes. We have to remove this checking for the safer_check argument and leave the message :     
\# safer_check already checked above
As in the backbone.R file
Thanks !
In addition, we should write in english in the issues, in order for anyone to be able to read all the messages. Thanks !

**Comment by gael-millot** [comment]
Do not hesitate to push when one of the function has been updated.
And do not forget to git pull each time you start to work. Because I just forgot :o)
Thanks.

**Comment by Tintin2710** [comment]
Monsieur j'ai rencontré un problème, j'ai déjà localement installé saferDev mais y toujours une erreur
![image](https://github.com/user-attachments/assets/f468a8a4-5bbc-4c69-98a0-ee639cdfebdb)
![屏幕截图 2024-11-15 172816](https://github.com/user-attachments/assets/8bce87bf-64a4-4f2f-bb32-30666b23d3ba)

**Comment by gael-millot** [comment]
It is probably because the package is not installed in a correct place locally and that the one you detect is an old version of saferDev.
Can you erase the saferDev folder from the path indeicatd by find.package() ?
then : 
open R as admin and remotes::install_github("https://github.com/safer-r/saferDev", lib = "C:/Program Files/R/R-4.3.1/library")
?
Otherwise, can you send me the instruction that leads to the error ?
PS : and write in english please ?:o)

**Comment by Tintin2710** [comment]
Ok sir
── Failure ('test-report.R:26:5'): report() ────────────────────────────────────
Expected `report(...)` to run without any errors.
ℹ Actually got a <simpleError> with text:
  
  
  ================
  
  ERROR IN report() OF THE saferDev PACKAGE
  REQUIRED PACKAGE:
  saferDev
  MUST BE INSTALLED IN ONE OF THESE FOLDERS:
  /__w/saferDev/saferDev/check/saferDev.Rcheck/tests/testthat
  /usr/local/lib/R/library
  
  ================

And I downloaded saferDve correctly. But threre is always the same error
![屏幕截图 2024-11-15 191211](https://github.com/user-attachments/assets/a6500b21-1d6b-4b92-9ec2-99685998f62f)
![image](https://github.com/user-attachments/assets/89c504f8-1037-4169-b988-545bb084cf2f)

**Comment by Tintin2710** [comment]
Sir i need to say this is very strange because i just retried to push get_message function which has passed the examination this morning and failed just few minutes ago.

**Comment by gael-millot** [comment]
Do you have the error during the continuous integration or locally ?
In addition, possible for you to write more info in each commit ? At least the name of the file modified ? So that it is easier to know which commit I have to open ? Thanks.

**Comment by gael-millot** [comment]
This error : 
Failure ('test-report.R:26:5'): report() 
tells you that it happens in the test-report file. Thus, I would run this file locally to see what happens.

**Comment by Tintin2710** [comment]
Sir I checked i found that the ERROR message is located in internal__function:
if( ! base::all(pkg.log)){
        tempo <- pkg.name[ ! pkg.log]
        tempo.cat <- base::paste0(
            "ERROR IN ", 
            external_function_name, 
            " OF THE ", external_package_name, " PACKAGE\nREQUIRED PACKAGE", 
            base::ifelse(base::length(tempo) == 1L, base::paste0(":\n", tempo), base::paste0("S:\n", base::paste(tempo, collapse = "\n"))), 
            "\nMUST BE INSTALLED IN", 
            base::ifelse(base::length(lib_path) == 1L, "", " ONE OF THESE FOLDERS"), 
            ":\n", 
            base::paste(lib_path, collapse = "\n")
        )
        base::stop(base::paste0("\n\n================\n\n", tempo.cat, "\n\n================\n\n"), call. = FALSE) # == in base::stop() to be able to add several messages between ==
    }
I'm sure I've installed the saferDev package correctly locally, and the test file for is_function_here passed successfully locally. So I'm assuming it's a problem with the CI test.
![image](https://github.com/user-attachments/assets/64bc2b90-d869-4ad2-b441-c29ba783902b)

**Comment by Tintin2710** [comment]
Sir I rechecked this morning,
![屏幕截图 2024-11-18 125343](https://github.com/user-attachments/assets/21b458b6-e8c2-435d-9bca-cfe0c0af63da)
![屏幕截图 2024-11-18 125317](https://github.com/user-attachments/assets/d28f353c-51b6-4541-bf47-cb1bc37836a4)
It can be inferred from this that the CI system loads saferDev locally when detecting the code.
But the Error message:
![屏幕截图 2024-11-18 125714](https://github.com/user-attachments/assets/a473c2b6-88f5-45df-a31c-5a828f2e8d72)
It means the error message given by .pack_and_function_check in internal_function when doing a run of the test file, saferDev was not downloaded. Other modified functions, such as the env_check() function, didn't give error message because there is no expect_no_error() test, or the safer_check=FALSE setting does not call the check of the required function part.

So I think it is not a problem caused by that I don't have the saferDev package installed locally, or could you verify this by doing a push in your local area please?
Also I would like to ask if I still continue to modify the rest of the backbone according to the protocol?

**Comment by gael-millot** [comment]
Hi. Yes you can continue, according to the protocol.

**Comment by Tintin2710** [comment]
Yes Sir∠(°ゝ°)

**Comment by gael-millot** [comment]
I am looking at the error.
I can already tell that my last commit was green And that with colons_checks() and test-colons_check, and also with all_args_here() and test-all_args_here, no error message was returned while safer_check was TRUE or FALSE in examples and that the presence of saferDev::arg_check was tested.

    ######## check of the required functions from the required packages
    if(safer_check == TRUE){
        saferDev:::.pack_and_function_check(
            fun = base::c(
                "saferDev::arg_check" # write each function preceeded by their package name
            ),
            lib_path = NULL, # write NULL if your function does not have any lib_path argument
            external_function_name = function_name,
            external_package_name = package_name
        )
    }
    ######## end check of the required functions from the required packages

**Comment by gael-millot** [comment]
1) When I compare backbone.R last version and the last version of is_function_here.R, I see lots of differences that should not be present. In fact, the procedure of the Backbone is to copy-paste all the backbone before the main code section, and then replace the parts that have to be adapted or empty the section.

2) In is_function_here.R (and other functions) you can only write  lib_path = NULL here   : 

        saferDev:::.pack_and_function_check(
            fun = base::c(
                "saferDev::arg_check"
            ),
            lib_path = NULL, # NULL if the function does not have any lib_path argument

If no lib_path argument. But is_function_here() has the lib_path argument. So it must be written : 
lib_path = lib_path
If it creates problem, it is somewhere else I would say, but not beacause of lib_path = lib_path.

**Comment by gael-millot** [comment]
In VS code, it is easy to compare the code of two files. This can help to paste the Backbone and then complete/update/empty. Ok ?

**Comment by Tintin2710** [comment]
Oh yes， i will correct that>
Yes，i always use VSCode to edit and compare the code.

**Comment by gael-millot** [comment]
I have emptied the cache in Actions. Let see if that helps.

**Comment by Tintin2710** [comment]
> 1. When I compare backbone.R last version and the last version of is_function_here.R, I see lots of differences that should not be present. In fact, the procedure of the Backbone is to copy-paste all the backbone before the main code section, and then replace the parts that have to be adapted or empty the section.
> 2. In is_function_here.R (and other functions) you can only write  lib_path = NULL here   :
>    ```
>     saferDev:::.pack_and_function_check(
>         fun = base::c(
>             "saferDev::arg_check"
>         ),
>         lib_path = NULL, # NULL if the function does not have any lib_path argument
>    ```
> 
> If no lib_path argument. But is_function_here() has the lib_path argument. So it must be written : lib_path = lib_path If it creates problem, it is somewhere else I would say, but not beacause of lib_path = lib_path.

Ah in fact I did replace the backbone all together and then pushed it, but since the last error message, I've been modifying the backbone of is_function_here step by step in order to make it easier to figure out what part of it is going wrong.

**Comment by gael-millot** [comment]
Ok. Let's create a branch named "haiding" and another one named "gael". Like that, you can test want you want on your "haiding" branch, and then merge with the main branch once you have solved your problem. What do you think ?
But warning : when you push, it is only the branch you are on. I think the best procedure is always to work on your own branch, push, push, push. And once you believe things are clean, git pull the main branch, merge your branch with the main and push the main branch. Ok ?

**Comment by Tintin2710** [comment]
> Ok. Let's create a branch named "haiding" and another one named "gael". Like that, you can test want you want on your "haiding" branch, and then merge with the main branch once you have solved your problem. What do you think ?

OKK!

**Comment by gael-millot** [comment]
And we should say "I work on this" regularly, in order to avoid merging problems. Right ?
And do not forget that files are not the same on your local folder, depending on the branch you have selected in the console. They correspond to those of the branch you have last selected.

**Comment by Tintin2710** [comment]
Okay no problem. I'm going to eat lunch  now and then later I'll change the backbone of is_function_here(*￣︶￣)

**Comment by Tintin2710** [comment]
So it seemes that is_funtion_here always has the same error i will work on is_package_here to change the backbone

**Comment by gael-millot** [comment]
I don't believe the problem comes from is_package_here() but more from the tests. I will work on that ok ?

**Comment by Tintin2710** [comment]
> I don't believe the problem comes from is_package_here() but more from the tests. I will work on that ok ?

OK, let's go!

**Comment by gael-millot** [comment]
Error solved. It is indeed in the test files. We have to systematically use safer_check = FALSE in test files.

**Comment by gael-millot** [comment]
Warning : in env_check, there is no warning in the main code. So
```
    #### warning output
    if( ! base::is.null(x = warn)){
        base::on.exit(expr = base::warning(base::paste0("FROM ", function_name, base::ifelse(test = base::is.null(x = package_name), yes = "", no = base::paste0(" OF THE ", package_name, " PACKAGE", collapse = NULL, recycle0 = FALSE)), "\n\n", warn, collapse = NULL, recycle0 = FALSE), call. = FALSE, immediate. = FALSE, noBreaks. = FALSE, domain = NULL), add = FALSE, after = TRUE)
        }
        base::on.exit(expr = base::options(warning.length = ini_warning_length), add = TRUE, after = TRUE)
    #### end warning output
```
Must not be added. 
Please : check everywhere that is is added only if there are warn initiation in the main code. Thanks !

**Comment by gael-millot** [comment]
Why in env_check, it is written :  
```
    tempo_log <- base::sapply( X = base::lapply(X = tempo_arg, FUN = function(x){base::get(x = x, pos = -1L, envir = base::parent.frame(n = 2), mode = "any", inherits = FALSE)}), FUN = function(x){base::is.character(x = x) & base::length(x = x) == 0}, simplify = TRUE, USE.NAMES = TRUE) # parent.frame(n = 2) because sapply(lapply())  # for character argument that can also be NULL, if NULL -> considered as character
```
And not what is written in the backbone : 
```
    tempo_log <- ! base::sapply(X = base::lapply(X = tempo_arg, FUN = function(x){base::get(x = x, pos = -1L, envir = base::parent.frame(n = 2), mode = "any", inherits = FALSE)}), FUN = function(x){if(base::is.null(x = x)){base::return(TRUE)}else{base::all(base::mode(x = x) == "character", na.rm = TRUE)}}, simplify = TRUE, USE.NAMES = TRUE) # parent.frame(n = 2) because sapply(lapply())  # for character argument that can also be NULL, if NULL -> considered as character
```
Soory I made a mistake!

**Comment by Tintin2710** [comment]
> Warning : in env_check, there is no warning in the main code. So
> 
> ```
>     #### warning output
>     if( ! base::is.null(x = warn)){
>         base::on.exit(expr = base::warning(base::paste0("FROM ", function_name, base::ifelse(test = base::is.null(x = package_name), yes = "", no = base::paste0(" OF THE ", package_name, " PACKAGE", collapse = NULL, recycle0 = FALSE)), "\n\n", warn, collapse = NULL, recycle0 = FALSE), call. = FALSE, immediate. = FALSE, noBreaks. = FALSE, domain = NULL), add = FALSE, after = TRUE)
>         }
>         base::on.exit(expr = base::options(warning.length = ini_warning_length), add = TRUE, after = TRUE)
>     #### end warning output
> ```
> 
> Must not be added. Please : check everywhere that is is added only if there are warn initiation in the main code. Thanks !

OK! I wiil check all the function after!

**Comment by gael-millot** [comment]
Hi. Do not forget to test the function with the examples (or the test file) before pushing. Right ?

**Comment by Tintin2710** [comment]
OK！

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gael-millot ***@***.***>
发送时间: Tuesday, November 19, 2024 1:34:49 PM
收件人: safer-r/saferDev ***@***.***>
抄送: Haiding WANG ***@***.***>; Comment ***@***.***>
主题: Re: [safer-r/saferDev] fit the new backbone to all functions (Issue #27)


Hi. Do not forget to test the function with the examples (or the test file) before pushing. Right ?

―

**Comment by gael-millot** [comment]
about x = name, once the new backbone issue will be done for all the saferDev functions, 
there is an issue that is to use colons_check, and then all_args_here on all saferDev functions (except colons_check and all_args_here), including internal functions, in order to complete them for package:: dependency and for all the args to add.

**Comment by Tintin2710** [comment]
> about x = name, once the new backbone issue will be done for all the saferDev functions, there is an issue that is to use colons_check, and then all_args_here on all saferDev functions (except colons_check and all_args_here), including internal functions, in order to complete them for package:: dependency and for all the args to add.

For this commit, I changed the name to x = name
![image](https://github.com/user-attachments/assets/64ea7166-27ba-4c76-832b-71a74f1afc45)

**Comment by gael-millot** [comment]
Hello. Could you tell me when the new backbone will be added to all saferDev function ? Thanks.

**Comment by Tintin2710** [comment]
Hello, I have already added the new backbone to all saferDev functions, I'm using colons_check() and all_args_here() to check all the functions

**Comment by gael-millot** [comment]
Excellent ! Thanks !

**Comment by Tintin2710** [comment]
1. After the check of colons_check, all the functions excepte functioon get_message, because it has one function created inside the main code which don't need to add :: 
![image](https://github.com/user-attachments/assets/48c84ede-4dd7-4f99-b776-29e8ce070af3)
2.The result of all_args_here() checking all functions is a bit strange，for example arg_check()
![image](https://github.com/user-attachments/assets/86d30eac-12eb-4c9b-853e-8dff1ffc8b45)

**Comment by gael-millot** [comment]
Hum. If this issue is done. Why not close it ? Push to say it is closed ? And post your new messages on the correct issue ? What do you think ?

**Comment by Tintin2710** [comment]
> Hum. If this issue is done. Why not close it ? Push to say it is closed ? And post your new messages on the correct issue ? What do you think ?

ok why not

**Comment by gael-millot** [comment]
Thus, could you copy-paste your last concern in the correct issue ? If still a concern ? Thanks.

**Comment by Tintin2710** [comment]
> Thus, could you copy-paste your last concern in the correct issue ? If still a concern ? Thanks.

Ok. And for internal_functions, we don't need to change their backbones right?

**Comment by gael-millot** [comment]
Good question. If we have, I will do it. Thanks !
