### ISSUE TITLE
add the checking of safer_check argument by arg_check() in all functions

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#28]

**Comment by Tintin2710** [comment]
Sir I found that we aren't check the argument data by arg_check in the funtion report, is it missed or dosen't need to be checked?

**Comment by gael-millot** [comment]
Expected. Because data can have many types, as written in the main code.

**Comment by Tintin2710** [comment]
> Expected. Because data can have many types, as written in the main code.

so we don't need to check it with arg_check() as it can have many types

**Comment by gael-millot** [comment]
Exact.
