### ISSUE TITLE
change `if( ! (base::all(base::class(arg.user.setting) == "list"`

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#3]
See
https://github.com/safer-r/ggcute/issues/3

**Comment by Tintin2710** [comment]
1. In arg_check.R, not found
2. arg_test done
3. env_check done
4. get_message.R done
5. Not found in internal_functions.R
6. is_functions_here.R done
7. is_package_here.R done
8. is_python_package_here.R done
9. report.R done

**Comment by gael-millot** [comment]
update now made for two_colons_check()
