### ISSUE TITLE
problem with arg_check() in all functions

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#31]
replace:
    ee <- base::expression(argum.check = base::c(argum.check, tempo$problem) , text.check = base::c(text.check, tempo$text) , checked.arg.names = base::c(checked.arg.names, tempo$object.name))
by:
    ee <- base::expression(argum.check <- base::c(argum.check, tempo$problem) , text.check <- base::c(text.check, tempo$text) , checked.arg.names <- base::c(checked.arg.names, tempo$object.name))

The = is a problem and must replaced by <-

**Comment by gael-millot** [comment]
Normally, this is solved in the backbone. So when the backbone code is integrated, this solve the problem.

**Comment by Tintin2710** [comment]
all done
