### ISSUE TITLE
add package.name argument to arg_check() and add this argument in all arg_check( used in all functions

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#32]

**Comment by Tintin2710** [comment]
Sir I have one question, in the function all_args_here(), why the pack_name = NULL instead of pack_name = package_name in the backbone? I think this should be changed right?
![image](https://github.com/user-attachments/assets/dc868058-c881-4cb7-b0d8-6eceb3cce0de)

**Comment by gael-millot** [comment]
Indeed. Well done !

**Comment by gael-millot** [comment]
The reason why this issue has been posted :o)

**Comment by Tintin2710** [comment]
> The reason why this issue has been posted :o)

So the package.name argument "pack_name" has been added to arg_check() , i think this issue has solved

**Comment by gael-millot** [comment]
If you have check alla arg_check() in all saferDev function, super nice ! Thanks ! You can indeed close it.

**Comment by Tintin2710** [comment]
> If you have check alla arg_check() in all saferDev function, super nice ! Thanks ! You can indeed close it.

I am modifying this function, and the test file shows that the result and expected do not match.  I will try to figure it out

**Comment by gael-millot** [comment]
Have you tested the test file locally ? Usually, the error shows up (no need to wait for the CI result).

**Comment by Tintin2710** [comment]
Yes, I'm checking it locally

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gael-millot ***@***.***>
发送时间: Wednesday, November 20, 2024 2:25:44 PM
收件人: safer-r/saferDev ***@***.***>
抄送: Haiding WANG ***@***.***>; Comment ***@***.***>
主题: Re: [safer-r/saferDev] add package.name argument to arg_check() and add this argument in all arg_check( used in all functions (Issue #32)


Have you tested the test file locally ? Usually, the error shows up (no need to wait for the CI result).

―

**Comment by Tintin2710** [comment]
Ok i found it, it is the part #waning i added in the all_args_here() cause the problem
![image](https://github.com/user-attachments/assets/d85ecc9f-4ae7-49f2-8105-4d09fc9b3d68)
Is this part should added into the function?

**Comment by gael-millot** [comment]
My apology. It is not very clear in the protocole of the Backbone. I will rewrite it.
You must not modify the main code, exept if there are already warning lines in it. In such case, you have to use the ######## Warning section indicated, adapting the yellow part.
Idem with reserved words.
Thanks !

**Comment by gael-millot** [comment]
PS : and also add the #### warning output section.

**Comment by gael-millot** [comment]
It was not already done for all_args_here ?

**Comment by Tintin2710** [comment]
> PS : and also add the #### warning output section.

fah okay, so it means that don't need to add the lines in the ####warning part, just leave this part empty?

**Comment by Tintin2710** [comment]
> > PS : and also add the #### warning output section.
> 
> fah okay, so it means that don't need to add the lines in the ####warning part, just leave this part empty? Because in the begining, the function all_args_here() doesn't have ########warning section in the main code

**Comment by Tintin2710** [comment]
> My apology. It is not very clear in the protocole of the Backbone. I will rewrite it. You must not modify the main code, exept if there are already warning lines in it. In such case, you have to use the ######## Warning section indicated, adapting the yellow part. Idem with reserved words. Thanks !

OK! Corrected and pushed the funtion all_args_here()
