### ISSUE TITLE
tests/testthat/test-internal_function.R copy paste in all packages what is written in this file for .pack_and_function_check() and .base_op_check()

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#33]

**Comment by Tintin2710** [comment]
for all the package?

**Comment by gael-millot** [comment]
This issue says that all safer packages should have a test-internal_function.R
And because all safer package have .pack_and_function_check() and .base_op_check()
in internal_function.R, at least copy / paste these tests in the test-internal_function.R of the other packages if not already done yet. Thanks

**Comment by Tintin2710** [comment]
> This issue says that all safer packages should have a test-internal_function.R And because all safer package have .pack_and_function_check() and .base_op_check() in internal_function.R, at least copy / paste these tests in the test-internal_function.R of the other packages if not already done yet. Thanks

Ok!

**Comment by Tintin2710** [comment]
All packages have added

**Comment by gael-millot** [comment]
Thanks !
