### ISSUE TITLE
change everywhere the end of the warning

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#35]
replace:
 base::on.exit(base::warning(base::paste0("FROM ", function.name, ":\n\n", warn), call. = FALSE))
by:
 base::on.exit(base::warning(base::paste0("FROM ", function.name, " OF THE ", package.name, " PACKAGE\n\n", warn), call. = FALSE))

**Comment by Tintin2710** [comment]
all functions in saferDev have solved.

**Comment by gael-millot** [comment]
Great ! Thanks !
