### ISSUE TITLE
complete test-internal_functions.R

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#36]

**Comment by gael-millot** [comment]
See test-all_args_here.R as an example. The aim is to increase covcode.

**Comment by Tintin2710** [comment]
Sir, this issue aims to complete package::function?

**Comment by gael-millot** [comment]
Not only but yes.
It is also to add new tests, like

``` 
    testthat::expect_error(saferDev::all_args_here(x = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, export = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, path_out = 1))
    testthat::expect_error(saferDev::all_args_here(x = test2, path_out = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, df_name = 1))
    testthat::expect_error(saferDev::all_args_here(x = test2, overwrite = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, lib_path = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, safer_check = "a")
```

to increase the covcode, meaning the coverage of the code of the function by the tests. Ok ?

**Comment by Tintin2710** [comment]
yes i have done

**Comment by gael-millot** [comment]
But in this issue, it consists to add tests for all of the functions in the internal .R file

**Comment by Tintin2710** [comment]
> But in this issue, it consists to add tests for all of the functions in the internal .R file

yes, i have added some tests in some functions you can see the commit

**Comment by Tintin2710** [comment]
![屏幕截图 2024-11-28 174319](https://github.com/user-attachments/assets/a7c9ec5f-4796-4212-84c5-7e4e4428e598)
![屏幕截图 2024-11-28 174252](https://github.com/user-attachments/assets/094cf677-3bc5-453c-848f-5e5f0d9b6ec8)
![屏幕截图 2024-11-28 174239](https://github.com/user-attachments/assets/23cb6a05-6d0f-4cf5-a280-4f3eb6e10664)
Yeah!!

**Comment by gael-millot** [comment]
Excellent ! Thanks !

**Comment by gael-millot** [comment]
The aim would be to be over 80% for each function ?
https://app.codecov.io/github/safer-r/saferDev?search=&branch=master&displayType=list

**Comment by Tintin2710** [comment]
> The aim would be to be over 80% for each function ? https://app.codecov.io/github/safer-r/saferDev?search=&branch=master&displayType=list

I've added quite a few tests in arg_test, and I'm now trying to raise the codcov of arg_check. 80%? I'm not sure about it. But I'll try to get codcov as high as I can.

**Comment by Tintin2710** [comment]
I have added tests for all of the functions in the saferDev.

**Comment by gael-millot** [comment]
Some functions inside internal_functions are not tested yet in test-internal_functions.R
So, issue reopened. Thanks.
