### ISSUE TITLE
complete test- for all functions

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#50]

**Comment by gael-millot** [comment]
See test-all_args_here.R as an example. The aim is to increase covcode.

**Comment by Tintin2710** [comment]
all test files in saferDev have been completed, i think we can close it

**Comment by gael-millot** [comment]
Woo. Amazing ! Thanks ! However, the covecod is still at 68%. We will have to think to increase this value. Which could be done by using safer_check = TRUE, except that it generates an error in CI... Grr

**Comment by gael-millot** [comment]
Maybe keep it open for now. Notably because we could had more checkings, like in test-all_args_check

``` 
    testthat::expect_error(saferDev::all_args_here(x = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, export = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, path_out = 1))
    testthat::expect_error(saferDev::all_args_here(x = test2, path_out = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, df_name = 1))
    testthat::expect_error(saferDev::all_args_here(x = test2, overwrite = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, lib_path = "a"))
    testthat::expect_error(saferDev::all_args_here(x = test2, safer_check = "a"))
```

**Comment by Tintin2710** [comment]
> Maybe keep it open for now. Notably because we could had more checkings, like in test-all_args_check
> 
> ```
>     testthat::expect_error(saferDev::all_args_here(x = "a"))
>     testthat::expect_error(saferDev::all_args_here(x = test2, export = "a"))
>     testthat::expect_error(saferDev::all_args_here(x = test2, path_out = 1))
>     testthat::expect_error(saferDev::all_args_here(x = test2, path_out = "a"))
>     testthat::expect_error(saferDev::all_args_here(x = test2, df_name = 1))
>     testthat::expect_error(saferDev::all_args_here(x = test2, overwrite = "a"))
>     testthat::expect_error(saferDev::all_args_here(x = test2, lib_path = "a"))
>     testthat::expect_error(saferDev::all_args_here(x = test2, safer_check = "a"))
> ```

ok
