### ISSUE TITLE
all_args_here() checks all functions and the result is weird, it doesn’t show the result clearly

### ISSUE THREAD

**Issue by Tintin2710** [safer-r/saferDev#52]
The resulat of arg_check() in saferDev package
![屏幕截图 2024-11-20 111755](https://github.com/user-attachments/assets/ed6fe899-4d00-4f7c-8d40-357cb622944f)

**Comment by gael-millot** [comment]
I believe this is expected. When it is a big table, it is better to use export = TRUE

**Comment by Tintin2710** [comment]
OK

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gael-millot ***@***.***>
发送时间: Thursday, November 28, 2024 10:05:02 AM
收件人: safer-r/saferDev ***@***.***>
抄送: Haiding WANG ***@***.***>; Author ***@***.***>
主题: Re: [safer-r/saferDev] all_args_here() checks all functions and the result is weird, it doesn’t show the result clearly (Issue #52)


I believe this is expected. When it is a big table, it is better to use export = TRUE

―
