### ISSUE TITLE
finish dev/two_colons_check.R and add it in R/

### ISSUE THREAD

**Issue by gael-millot** [safer-r/saferDev#7]
1) finish the description part
2) add :: everywhere
3) make exemples and check that they work well
4) make the test.that file
5) Make the  .Rmd file

**Comment by Tintin2710** [comment]
un peu dee peoblème avec la fonction, car il manque certains functions

**Comment by gael-millot** [comment]
If we add two_colons_check.R in R/, we must write all the files for two_colons_check() (in man/, tests/ and vignettes/), as what has been done for the other functions of the saferDev package

**Comment by Tintin2710** [comment]
Ok

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gael-millot ***@***.***>
发送时间: Tuesday, April 23, 2024 11:47:47 AM
收件人: safer-r/saferDev ***@***.***>
抄送: Haiding WANG ***@***.***>; State change ***@***.***>
主题: Re: [safer-r/saferDev] finish dev/two_colons_check.R and add it in R/ (Issue #7)


If we add two_colons_check.R in R/, we must write all the files for two_colons_check() (in man/, tests/ and vignettes/), as what has been done for the other functions of the saferDev package

―

**Comment by Tintin2710** [comment]
don

> If we add two_colons_check.R in R/, we must write all the files for two_colons_check() (in man/, tests/ and vignettes/), as what has been done for the other functions of the saferDev package

done

**Comment by Tintin2710** [comment]
j'ai écrit certaines simple exemple dans test.that fichier
